# 生产环境配置 ----- linux
spring:
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123RollBook

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123RollBook
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/robok?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false

    # Druid配置
    druid:
      access-to-underlying-connection-allowed: true
      # 配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      # CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      # 最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      # 可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      # 保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # MVC配置
  mvc:
    throw-exception-if-no-handler-found: true
    # swagger-ui启动配置
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # MQTT配置
  mqtt:
    username: admin
    password: 123RollBook
    url: tcp://120.25.144.59:1883
    client:
      id: mqttx_b11a7a81
    default:
      topic: RoServe/usr/roll

# 服务配置
server:
  ip: tqnnan.top
  port: 8899
  compression:
    enabled: true
  servlet:
    context-path: /api

# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 微信小程序相关配置
wx-app: {
  app-secret: f259a9d4f7fbf17f4ac96a058e8d0de7,
  appID: wx5260f83aed33c580
}

# 上传文件夹路径
my-path: img/

# 生产环境关闭swagger
springfox:
  documentation:
    # 总开关（同时设置auto-startup=false，否则/v3/api-docs等接口仍能继续访问）
    enabled: false
    auto-startup: false
    swagger-ui:
      enabled: false
