# 开发环境配置 ----- windows 11
spring:
  # redis配置
  redis:
    host: localhost
    port: 6379
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/robok?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  # swagger-ui启动配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
# 服务配置
server:
  port: 8899
  compression:
    enabled: true
  servlet:
    context-path: /api
# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# 微信小程序相关配置
wx-app: {
  app-secret: f259a9d4f7fbf17f4ac96a058e8d0de7,
  appID: wx5260f83aed33c580
}
# 上传文件夹路径
my-path: .\\robokserver\\robok-web\\src\\main\\resources\\static\\
logging:
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
